# This viminfo file was generated by Vim 8.1.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~h
# Last Search Pattern:
~MSle0~/2015\c

# Command Line History (newest to oldest):
:w
|2,0,1537883493,,"w"
:q
|2,0,1537884030,,"q"
:<F12><F12><F12>
|2,0,1537883891,,"<F12><F12><F12>"
:<F12><F12><F12><F12><F12>
|2,0,1537883844,,"<F12><F12><F12><F12><F12>"
:q!
|2,0,1537883530,,"q!"
:!python %
|2,0,1537883053,,"!python %"
:YcmDebugInfo
|2,0,1537882932,,"YcmDebugInfo"
:YcmCompleter
|2,0,1537882920,,"YcmCompleter"
:!q
|2,0,1537879125,,"!q"
:bd
|2,0,1537878561,,"bd"
:BundleClean
|2,0,1537801459,,"BundleClean"
:BundleInstall
|2,0,1537788135,,"BundleInstall"
:Bundle
|2,0,1537788133,,"Bundle"
:!
|2,0,1537772343,,"!"
:e!
|2,0,1529938118,,"e!"
:%retab
|2,0,1529933992,,"%retab"
::q
|2,0,1529932713,,":q"
:set expandtab
|2,0,1529931964,,"set expandtab"
:source ~/.vim/viminfo
|2,0,1529931465,,"source ~/.vim/viminfo"
:e !
|2,0,1529779005,,"e !"
:w!
|2,0,1529778988,,"w!"
:wbd
|2,0,1529778017,,"wbd"
:source .vim/vimrc
|2,0,1529778004,,"source .vim/vimrc"
:source ~/.vim/vimrc
|2,0,1529744091,,"source ~/.vim/vimrc"
:ls
|2,0,1529740665,,"ls"
:b1
|2,0,1529740577,,"b1"
:exit
|2,0,1529740553,,"exit"
:b2
|2,0,1529740539,,"b2"
:w autostart.sh
|2,0,1529585556,,"w autostart.sh"
:W
|2,0,1529505712,,"W"
:delmarks a
|2,0,1529497687,,"delmarks a"
:w !sudo tee %
|2,0,1529420715,,"w !sudo tee %"
:w sudo tee %
|2,0,1529420701,,"w sudo tee %"
:!w sudo tee %
|2,0,1529417115,,"!w sudo tee %"
:'<,'>
|2,0,1529414774,,"'<,'>"
:AutoRead
|2,0,1529240927,,"AutoRead"
:help 'autoread'
|2,0,1529240005,,"help 'autoread'"
:w bak
|2,0,1529237499,,"w bak"
:sv
|2,0,1529182061,,"sv"
:vs
|2,0,1529182027,,"vs"
:w html.txt
|2,0,1529063895,,"w html.txt"
:source ~..vim/vimrc
|2,0,1528896583,,"source ~..vim/vimrc"
:while 
|2,0,1528895832,,"while "
:with 
|2,0,1528895708,,"with "
:open
|2,0,1528895636,,"open"
:        with contextlib.closing(                mmap.mmap(f.filen
|2,0,1528895624,,"        with contextlib.closing(                mmap.mmap(f.filen"
:print
|2,0,1528895591,,"print"
:w! sudo tee%
|2,0,1528895528,,"w! sudo tee%"
:open /home/gaffey/Python/Learn/tool/client.py
|2,0,1528892084,,"open /home/gaffey/Python/Learn/tool/client.py"
:open ~/Python/Learn/tool/client.py
|2,0,1528892065,,"open ~/Python/Learn/tool/client.py"

# Search String History (newest to oldest):
? true
|2,1,1530285047,,"true"
? extend
|2,1,1530284898,,"extend"
? map
|2,1,1530284432,,"map"
? bpy
|2,1,1530284079,,"bpy"
? arr
|2,1,1530284018,,"arr"
?/t
|2,1,1530282604,47,"t"
??as
|2,1,1530282591,63,"as"
??bpy
|2,1,1530282395,63,"bpy"
? set
|2,1,1530283435,,"set"
? ma
|2,1,1530283393,,"ma"
? s
|2,1,1530283309,,"s"
? myT
|2,1,1530283233,,"myT"
?/set
|2,1,1530282994,47,"set"
??plugin
|2,1,1530282967,63,"plugin"
?/\vlugin 
|2,1,1530282951,47,"\\vlugin "
?/autoin
|2,1,1529932527,47,"autoin"
?/softtabstop
|2,1,1529932300,47,"softtabstop"
?/autoindent
|2,1,1529932104,47,"autoindent"
?/soft
|2,1,1529931991,47,"soft"
? \<必要模块\>
|2,1,1529741837,,"\\<必要模块\\>"
?/w
|2,1,1529694660,47,"w"
?/border
|2,1,1529237511,47,"border"
?/bor
|2,1,1529237474,47,"bor"
?/view3d.
|2,1,1529237452,47,"view3d."
?/view3d_to_select
|2,1,1529236716,47,"view3d_to_select"
?/VIE3D
|2,1,1529236970,47,"VIE3D"
?/http://images.adsttc.com.qtlcn.com/media/images/5942/4c15/b22e/3848/9c00/00e1/slideshow/Nueva_Sede_EDU_-_Foto._Alejandro_Arango_(33).jpg?1497517064
|2,1,1529063880,47,"http://images.adsttc.com.qtlcn.com/media/images/5942/4c15/b22e/3848/9c00/00e1/slideshow/Nueva_Sede_EDU_-_Foto._Alejandro_Arango_(33).jpg?1497517064"
?/59424c15b22e38489c0000e1
|2,1,1529063690,47,"59424c15b22e38489c0000e1"
?/59424b52b22e38489c0000cd
|2,1,1529063524,47,"59424b52b22e38489c0000cd"
?/在线
|2,1,1528978957,47,"在线"
?/Baahubali
|2,1,1528895367,47,"Baahubali"
?/sql
|2,1,1528558640,47,"sql"
?/start*
|2,1,1528558201,47,"start*"

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@y
|2,3,1537801460,,"y"
@/home/gaffey/Learn/Util/ThreadUtil.py
|2,3,1529935916,,"/home/gaffey/Learn/Util/ThreadUtil.py"
@/home/gaffey/Learn/Util/BpyUtil.py
|2,3,1529935480,,"/home/gaffey/Learn/Util/BpyUtil.py"

# Debug Line History (newest to oldest):

# Registers:
"0	LINE	0
	vnoremap <F12> :w !python<CR>
|3,0,0,1,1,0,1537883760,"vnoremap <F12> :w !python<CR>"
"1	LINE	0
	vnoremap <F12> :w !python<CR>
|3,0,1,1,1,0,1537883787,"vnoremap <F12> :w !python<CR>"
"2	LINE	0
	cnoremap <F12> :w !python<CR>
|3,0,2,1,1,0,1537883784,"cnoremap <F12> :w !python<CR>"
"3	LINE	0
	vnoremap 
|3,0,3,1,1,0,1537883624,"vnoremap "
"4	LINE	0
	# -*- coding: utf-8 -*-
|3,0,4,1,1,0,1537883528,"# -*- coding: utf-8 -*-"
"5	LINE	0
	mxnet.
|3,0,5,1,1,0,1537883181,"mxnet."
"6	LINE	0
	map <F10> ma:0,$!yapf --style='{based_on_style:pep8,column_limit:120}'<CR> `a
|3,0,6,1,1,0,1537883148,"map <F10> ma:0,$!yapf --style='{based_on_style:pep8,column_limit:120}'<CR> `a"
"7	LINE	0
	map <F8> :call Mpv()<CR><<CR><CR>
|3,0,7,1,1,0,1537883145,"map <F8> :call Mpv()<CR><<CR><CR>"
"8	LINE	0
	map <F12> :w !python<CR>
|3,0,8,1,1,0,1537883138,"map <F12> :w !python<CR>"
"9	LINE	0
	mxne
|3,0,9,1,1,0,1537883069,"mxne"
"a	LINE	0
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
	    tree = parser_driver.parse_string(code, debug=False)
	  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
	    return self.parse_tokens(tokens, debug)
	  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
	    if p.addtoken(type, value, (prefix, start)):
	  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
	    raise ParseError("bad input", type, value, context)
	lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (36, 15))
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 121, in ParseCodeToTree
	    tree = parser_driver.parse_string(code, debug=False)
	  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 107, in parse_string
	    return self.parse_tokens(tokens, debug)
	  File "/usr/lib/python3.6/lib2to3/pgen2/driver.py", line 72, in parse_tokens
	    if p.addtoken(type, value, (prefix, start)):
	  File "/usr/lib/python3.6/lib2to3/pgen2/parse.py", line 159, in addtoken
	    raise ParseError("bad input", type, value, context)
	lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (36, 15))
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "/usr/bin/yapf", line 11, in <module>
	    sys.exit(run_main())
	  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 313, in run_main
	    sys.exit(main(sys.argv))
	  File "/usr/lib/python3.6/site-packages/yapf/__init__.py", line 183, in main
	    verify=args.verify)
	  File "/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py", line 129, in FormatCode
	    tree = pytree_utils.ParseCodeToTree(unformatted_source)
	  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 127, in ParseCodeToTree
	    raise e
	  File "/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py", line 125, in ParseCodeToTree
	    ast.parse(code)
	  File "/usr/lib/python3.6/ast.py", line 35, in parse
	    return compile(source, filename, mode, PyCF_ONLY_AST)
	  File "<unknown>", line 36
	    with outputfile=open(fileurl,'wb') as f:
	                   ^
	SyntaxError: invalid syntax
|3,0,10,1,45,0,1528977822,"Traceback (most recent call last):","  File \"/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py\", line 115, in ParseCodeToTree","    tree = parser_driver.parse_string(code, debug=False)","  File \"/usr/lib/python3.6/lib2to3/pgen2/driver.py\", line 107, in parse_string","    return self.parse_tokens(tokens, debug)","  File \"/usr/lib/python3.6/lib2to3/pgen2/driver.py\", line 72, in parse_tokens",>50
|<"    if p.addtoken(type, value, (prefix, start)):","  File \"/usr/lib/python3.6/lib2to3/pgen2/parse.py\", line 159, in addtoken","    raise ParseError(\"bad input\", type, value, context)","lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (36, 15))","","During handling of the above exception, another exception occurred:","","Traceback (most recent call last):",>104
|<"  File \"/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py\", line 121, in ParseCodeToTree","    tree = parser_driver.parse_string(code, debug=False)","  File \"/usr/lib/python3.6/lib2to3/pgen2/driver.py\", line 107, in parse_string","    return self.parse_tokens(tokens, debug)","  File \"/usr/lib/python3.6/lib2to3/pgen2/driver.py\", line 72, in parse_tokens","    if p.addtoken(type, value, (prefix, start)):",>77
|<"  File \"/usr/lib/python3.6/lib2to3/pgen2/parse.py\", line 159, in addtoken","    raise ParseError(\"bad input\", type, value, context)","lib2to3.pgen2.parse.ParseError: bad input: type=22, value='=', context=('', (36, 15))","","During handling of the above exception, another exception occurred:","","Traceback (most recent call last):","  File \"/usr/bin/yapf\", line 11, in <module>","    sys.exit(run_main())",>85
|<"  File \"/usr/lib/python3.6/site-packages/yapf/__init__.py\", line 313, in run_main","    sys.exit(main(sys.argv))","  File \"/usr/lib/python3.6/site-packages/yapf/__init__.py\", line 183, in main","    verify=args.verify)","  File \"/usr/lib/python3.6/site-packages/yapf/yapflib/yapf_api.py\", line 129, in FormatCode","    tree = pytree_utils.ParseCodeToTree(unformatted_source)","  File \"/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py\", line 127, in ParseCodeToTree",>13
|<"    raise e","  File \"/usr/lib/python3.6/site-packages/yapf/yapflib/pytree_utils.py\", line 125, in ParseCodeToTree","    ast.parse(code)","  File \"/usr/lib/python3.6/ast.py\", line 35, in parse","    return compile(source, filename, mode, PyCF_ONLY_AST)","  File \"<unknown>\", line 36","    with outputfile=open(fileurl,'wb') as f:","                   ^","SyntaxError: invalid syntax"
"t	CHAR	0
	I# -*- coding: utf-8 -*-
|3,0,29,0,1,0,1529740655,"I# -*- coding: utf-8 -*-"
""-	CHAR	0
	:
|3,1,36,0,1,0,1537884010,":"

# Buffer list:
%~/test.py	5	10

# History of marks within files (newest to oldest):

> ~/test.py
	*	1537884161	0
	"	5	10
	^	5	8
	.	5	7
	+	1	11
	+	1	0
	+	1	7
	+	1	0
	+	1	13
	+	1	16
	+	1	0
	+	1	11
	+	3	0
	+	1	12
	+	1	11
	+	1	12
	+	3	0
	+	1	10
	+	2	8
	+	3	11
	+	4	0
	+	5	7
	u	1	7

> ~/.vim/vimrc
	*	1537884084	0
	"	89	11
	^	86	4
	.	86	3
	+	48	0
	+	63	0
	+	69	0
	+	62	0
	+	1	0
	+	96	0
	+	90	5
	+	96	0
	+	57	0
	+	58	0
	+	97	0
	+	84	0
	+	90	0
	+	47	0
	+	48	0
	+	90	0
	+	100	5
	+	92	32
	+	94	39
	+	101	5
	+	101	12
	+	101	7
	+	101	12
	+	101	0
	+	94	0
	+	93	79
	+	93	104
	+	69	0
	+	84	12
	+	85	12
	+	84	12
	+	86	12
	+	85	37
	+	86	28
	+	85	38
	+	84	12
	+	103	0
	+	91	0
	+	90	0
	+	89	0
	+	90	0
	+	87	0
	+	90	0
	+	88	0
	+	87	3
	+	88	3
	+	89	3
	+	84	3
	+	85	3
	+	86	3
	u	102	42

> /usr/lib/python3.7/site-packages/numpy/__init__.py
	*	1537882781	0
	"	1	0

> /usr/lib/python3.7/os.py
	*	1537882774	0
	"	1	0

> ~/test.c
	*	1537880786	0
	"	1	0
	.	1	0
	+	1	0

> /usr/lib/python2.7/os.py
	*	1537880377	0
	"	1	0

> ~/.vim/bundle/YouCompleteMe/third_party/ycmd/examples/.ycm_extra_conf.py
	*	1537879157	0
	"	18	8
	u	19	8

> /usr/lib/python2.7/pkgutil.py
	*	1537878957	0
	"	19	0
	u	5	7

> ~/.config/privarcy/cron/SysBackup
	*	1537878956	0
	"	3	0
	.	1	0
	+	3	2
	+	3	22
	+	3	0
	+	1	10
	+	2	0
	+	3	0
	+	1	20
	+	1	0
	u	1	7

> ~/.config/blender/2.79/scripts/addons/HOps/developer_utils.py
	*	1537878588	0
	"	5	8
	u	5	8
